### ISSUE TITLE
Centos 8-stream packages are not considered

### ISSUE THREAD

**Issue by maxgio92** [maxgio92/krawler#15]
**Describe the bug**

`8-stream` version of Centos, is not considered when scraping a repository from mirrors, like: https://mirrors.edge.kernel.org/centos/8-stream/

**How to reproduce it**

With a config like:
```yaml
distros:
  centos:
    versions:
    - "8"
    archs:
    - "x86_64"
```
And the scraped URLs are visible during the process on stdout.

**Expected behaviour**

It should consider also non compliant-semver distro versions.
